// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/metrics/metrics.proto

package metricspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tick is one snapshot of every requested metric at a single instant.
// Using a map keeps the wire format identical to the monolith's WireSample
// JSON shape ({t, v:{cpu:..., memory:...}}) so the BFF can pass it through
// with only a JSON serialization step.
type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Values        map[string]float64     `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Tick) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Tick) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subset of metric names to stream. Empty = all known metrics.
	MetricNames   []string `protobuf:"bytes,1,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *StreamRequest) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

type HistoryRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MetricNames []string               `protobuf:"bytes,1,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"`
	// Inclusive lower bound of the time range (Unix ms).
	FromTimestampMs int64 `protobuf:"varint,2,opt,name=from_timestamp_ms,json=fromTimestampMs,proto3" json:"from_timestamp_ms,omitempty"`
	// Exclusive upper bound. 0 means "now".
	ToTimestampMs int64 `protobuf:"varint,3,opt,name=to_timestamp_ms,json=toTimestampMs,proto3" json:"to_timestamp_ms,omitempty"`
	// Maximum points to return per metric (server-side downsample target).
	// 0 means no downsample.
	MaxPoints     int32 `protobuf:"varint,4,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

func (x *HistoryRequest) GetFromTimestampMs() int64 {
	if x != nil {
		return x.FromTimestampMs
	}
	return 0
}

func (x *HistoryRequest) GetToTimestampMs() int64 {
	if x != nil {
		return x.ToTimestampMs
	}
	return 0
}

func (x *HistoryRequest) GetMaxPoints() int32 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

var File_proto_metrics_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/metrics/metrics.proto\x12\ametrics\"\x97\x01\n" +
	"\x04Tick\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x121\n" +
	"\x06values\x18\x02 \x03(\v2\x19.metrics.Tick.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"2\n" +
	"\rStreamRequest\x12!\n" +
	"\fmetric_names\x18\x01 \x03(\tR\vmetricNames\"\xa6\x01\n" +
	"\x0eHistoryRequest\x12!\n" +
	"\fmetric_names\x18\x01 \x03(\tR\vmetricNames\x12*\n" +
	"\x11from_timestamp_ms\x18\x02 \x01(\x03R\x0ffromTimestampMs\x12&\n" +
	"\x0fto_timestamp_ms\x18\x03 \x01(\x03R\rtoTimestampMs\x12\x1d\n" +
	"\n" +
	"max_points\x18\x04 \x01(\x05R\tmaxPoints2\x83\x01\n" +
	"\x0eMetricsService\x129\n" +
	"\x0eStreamRealtime\x12\x16.metrics.StreamRequest\x1a\r.metrics.Tick0\x01\x126\n" +
	"\n" +
	"GetHistory\x12\x17.metrics.HistoryRequest\x1a\r.metrics.Tick0\x01BNZLgithub.com/KazukiKandaKK/webgrapgh/aws-microservices/proto/metrics;metricspbb\x06proto3"

var (
	file_proto_metrics_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_metrics_proto_rawDescData []byte
)

func file_proto_metrics_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_metrics_proto_rawDescData
}

var file_proto_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_metrics_metrics_proto_goTypes = []any{
	(*Tick)(nil),           // 0: metrics.Tick
	(*StreamRequest)(nil),  // 1: metrics.StreamRequest
	(*HistoryRequest)(nil), // 2: metrics.HistoryRequest
	nil,                    // 3: metrics.Tick.ValuesEntry
}
var file_proto_metrics_metrics_proto_depIdxs = []int32{
	3, // 0: metrics.Tick.values:type_name -> metrics.Tick.ValuesEntry
	1, // 1: metrics.MetricsService.StreamRealtime:input_type -> metrics.StreamRequest
	2, // 2: metrics.MetricsService.GetHistory:input_type -> metrics.HistoryRequest
	0, // 3: metrics.MetricsService.StreamRealtime:output_type -> metrics.Tick
	0, // 4: metrics.MetricsService.GetHistory:output_type -> metrics.Tick
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metrics_metrics_proto_init() }
func file_proto_metrics_metrics_proto_init() {
	if File_proto_metrics_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_metrics_proto = out.File
	file_proto_metrics_metrics_proto_goTypes = nil
	file_proto_metrics_metrics_proto_depIdxs = nil
}
