// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/logs/logs.proto

package logspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEvent mirrors the monolith's logs.Event JSON shape so BFF can re-emit
// it on /ws/logs without remapping fields.
type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_proto_logs_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_proto_logs_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_logs_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_logs_proto_rawDescGZIP(), []int{1}
}

type HistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max events to return. Server caps to its ring capacity.
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_logs_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_logs_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*LogEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_logs_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_logs_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryResponse) GetEvents() []*LogEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_logs_logs_proto protoreflect.FileDescriptor

const file_proto_logs_logs_proto_rawDesc = "" +
	"\n" +
	"\x15proto/logs/logs.proto\x12\x04logs\"\x85\x01\n" +
	"\bLogEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x0f\n" +
	"\rStreamRequest\"&\n" +
	"\x0eHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"9\n" +
	"\x0fHistoryResponse\x12&\n" +
	"\x06events\x18\x01 \x03(\v2\x0e.logs.LogEventR\x06events2\x80\x01\n" +
	"\n" +
	"LogService\x127\n" +
	"\x0eStreamRealtime\x12\x13.logs.StreamRequest\x1a\x0e.logs.LogEvent0\x01\x129\n" +
	"\n" +
	"GetHistory\x12\x14.logs.HistoryRequest\x1a\x15.logs.HistoryResponseBHZFgithub.com/KazukiKandaKK/webgrapgh/aws-microservices/proto/logs;logspbb\x06proto3"

var (
	file_proto_logs_logs_proto_rawDescOnce sync.Once
	file_proto_logs_logs_proto_rawDescData []byte
)

func file_proto_logs_logs_proto_rawDescGZIP() []byte {
	file_proto_logs_logs_proto_rawDescOnce.Do(func() {
		file_proto_logs_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logs_logs_proto_rawDesc), len(file_proto_logs_logs_proto_rawDesc)))
	})
	return file_proto_logs_logs_proto_rawDescData
}

var file_proto_logs_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_logs_logs_proto_goTypes = []any{
	(*LogEvent)(nil),        // 0: logs.LogEvent
	(*StreamRequest)(nil),   // 1: logs.StreamRequest
	(*HistoryRequest)(nil),  // 2: logs.HistoryRequest
	(*HistoryResponse)(nil), // 3: logs.HistoryResponse
}
var file_proto_logs_logs_proto_depIdxs = []int32{
	0, // 0: logs.HistoryResponse.events:type_name -> logs.LogEvent
	1, // 1: logs.LogService.StreamRealtime:input_type -> logs.StreamRequest
	2, // 2: logs.LogService.GetHistory:input_type -> logs.HistoryRequest
	0, // 3: logs.LogService.StreamRealtime:output_type -> logs.LogEvent
	3, // 4: logs.LogService.GetHistory:output_type -> logs.HistoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logs_logs_proto_init() }
func file_proto_logs_logs_proto_init() {
	if File_proto_logs_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logs_logs_proto_rawDesc), len(file_proto_logs_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logs_logs_proto_goTypes,
		DependencyIndexes: file_proto_logs_logs_proto_depIdxs,
		MessageInfos:      file_proto_logs_logs_proto_msgTypes,
	}.Build()
	File_proto_logs_logs_proto = out.File
	file_proto_logs_logs_proto_goTypes = nil
	file_proto_logs_logs_proto_depIdxs = nil
}
